image: docker:stable

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - docker info
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

stages:
  - build

# Build
Docker Image 1.21:
  stage: build
  only:
    - master
    - tags
  script:
    - >
      docker build -f 1.21/Dockerfile
      -t fabionaspolini/kubectl:1.21.3
      -t fabionaspolini/kubectl:1.21
      -t fabionaspolini/kubectl:latest
      ./1.21
    - docker push fabionaspolini/kubectl:1.21.3
    - docker push fabionaspolini/kubectl:1.21
    - docker push fabionaspolini/kubectl:latest

Docker Image 1.20:
  stage: build
  only:
    - master
    - tags
  script:
    - >
      docker build -f 1.20/Dockerfile
      -t fabionaspolini/kubectl:1.20.9
      -t fabionaspolini/kubectl:1.20
      ./1.20
    - docker push fabionaspolini/kubectl:1.20.9
    - docker push fabionaspolini/kubectl:1.20

Docker Image 1.19:
  stage: build
  only:
    - master
    - tags
  script:
    - >
      docker build -f 1.19/Dockerfile
      -t fabionaspolini/kubectl:1.19.3
      -t fabionaspolini/kubectl:1.19
      ./1.19
    - docker push fabionaspolini/kubectl:1.19.3
    - docker push fabionaspolini/kubectl:1.19
